#!/usr/bin/env python3
# Copyright (c) 2023 Random "Randy" Lattice and Sean Andersen
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://www.opensource.org/licenses/mit-license.php.
'''
Generate a C file with Hash-to-curve IETF test vectors (RFC 9380).
'''

import json
import sys

filename_input = sys.argv[1]

with open(filename_input) as f:
    doc = json.load(f)

def to_c_array(x):
    if x == "": return ""
    s = ',0x'.join(a+b for a,b in zip(x[::2], x[1::2]))
    return "0x" + s


num_vectors = len(doc['vectors'])

print("/* Note: this file was autogenerated using tests_frost_ietf_rfc9380_generate copy.py. Do not edit. */")
print(f"/*   Suite: {doc['suite']} */")
print(f"/*   Reference: {doc['url']} */")
print("")

print(f"#define IETF_RFC9380_DST_LEN {len(doc['dst'])}")
print(f"static const unsigned char ietf_rfc9380_dst[IETF_RFC9380_DST_LEN] = \"{doc['dst']}\";")
print("")

offset_msg_running = 0
msgs = ""
Px = ""
Py = ""
u0 = ""
u1 = ""
q0x = ""
q0y = ""
q1x = ""
q1y = ""
out = ""

len_Px = 0
len_Py = 0
len_u0 = 0
len_u1 = 0
len_q0x = 0
len_q0y = 0
len_q1x = 0
len_q1y = 0

struct_definition = """
typedef struct {
    size_t msg_offset;
    size_t msg_len;
} ietf_rfc9380_testvector;
"""

print(f"#define IETF_RFC9380_TEST_VECTORS {int(num_vectors)}")
print("")

print(struct_definition)
print("")

for i in range(num_vectors):
    vector = doc['vectors'][i]
    if len_Px == 0:
        len_Px = int(len(vector['P.x']) / 2)
    if len_Py == 0:
        len_Py = int(len(vector['P.y']) / 2)
    if len_u0 == 0:
        len_u0 = int(len(vector['u[0]']) / 2)
    if len_u1 == 0:
        len_u1 = int(len(vector['u[1]']) / 2)
    if len_q0x == 0:
        len_q0x = int(len(vector['Q0.x']) / 2)
    if len_q0y == 0:
        len_q0y = int(len(vector['Q0.y']) / 2)
    if len_q1x == 0:
        len_q1x = int(len(vector['Q1.x']) / 2)
    if len_q1y == 0:
        len_q1y = int(len(vector['Q1.y']) / 2)

    Px += f"{ to_c_array(vector['P.x'])}, \n"
    Py += f"{ to_c_array(vector['P.y'])}, \n"
    u0 += f"{ to_c_array(vector['u[0]'])}, \n"
    u1 += f"{ to_c_array(vector['u[1]'])}, \n"
    q0x += f"{ to_c_array(vector['Q0.x'])}, \n"
    q0y += f"{ to_c_array(vector['Q0.y'])}, \n"
    q1x += f"{ to_c_array(vector['Q1.x'])}, \n"
    q1y += f"{ to_c_array(vector['Q1.y'])}, \n"


    msg_len = len(vector['msg'])
    msg_offset = offset_msg_running
    
    if msg_len > 0:
        msgs += f"{ to_c_array(vector['msg'].encode('utf-8').hex())}, \n"
    
    out += f"  {{{msg_offset}, {msg_len} }},\n"
    offset_msg_running += msg_len


print(f"#define IETF_RFC9380_Px_SIZE {str(len_Px)}")
print(f"#define IETF_RFC9380_Py_SIZE {str(len_Py)}")
print(f"#define IETF_RFC9380_u0_SIZE {str(len_u0)}")
print(f"#define IETF_RFC9380_u1_SIZE {str(len_u1)}")
print(f"#define IETF_RFC9380_Q0x_SIZE {str(len_q0x)}")
print(f"#define IETF_RFC9380_Q0y_SIZE {str(len_q0y)}")
print(f"#define IETF_RFC9380_Q1x_SIZE {str(len_q1x)}")
print(f"#define IETF_RFC9380_Q1y_SIZE {str(len_q1y)}")
print("")

print(f"static const unsigned char ietf_rfc9380_pxs[] = {{{Px}}};")
print(f"static const unsigned char ietf_rfc9380_pys[] = {{{Py}}};")
print(f"static const unsigned char ietf_rfc9380_u0s[] = {{{u0}}};")
print(f"static const unsigned char ietf_rfc9380_u1s[] = {{{u1}}};")
print(f"static const unsigned char ietf_rfc9380_q0xs[] = {{{q0x}}};")
print(f"static const unsigned char ietf_rfc9380_q0ys[] = {{{q0y}}};")
print(f"static const unsigned char ietf_rfc9380_q1xs[] = {{{q1x}}};")
print(f"static const unsigned char ietf_rfc9380_q1ys[] = {{{q1y}}};")
print("")

print("static const unsigned char ietf_rfc9380_messages[]    = { " + msgs + "};\n")
print("")

print("static const ietf_rfc9380_testvector ietf_rfc9380_testvectors[IETF_RFC9380_TEST_VECTORS] = {")
print(out)
print("};")