name: Check that the version numbers contained in configure.ac and CMakeLists.txt are consistent to each other

on:
  push:
    branches:
      - frost
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  verify-version-consistency:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Check that the version numbers contained in configure.ac and CMakeLists.txt are consistent to each other
        run: scripts/verify-version-consistency.sh
